foreground         #ccddd9
background         #111111
background_opacity 1.0
cursor             #ccddd9

active_tab_foreground     #031010
active_tab_background     #ccddd9
inactive_tab_foreground   #ccddd9
inactive_tab_background   #031010

active_border_color   #ccddd9
inactive_border_color #031010
bell_border_color     #1B986F

color0       #111111
color8       #8e9a97
color1       #1B986F
color9       #1B986F
color2       #737F81
color10      #737F81
color3       #41A58E
color11      #41A58E
color4       #00DF82
color12      #00DF82
color5       #21CC91
color13      #21CC91
color6       #98AFAC
color14      #98AFAC
color7       #ccddd9
color15      #ccddd9
